// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "wit": Application Security
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-wit
// --version=v1.3.0

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

type (
	// Private type used to store auth handler info in request context
	authMiddlewareKey string
)

// UseJWTMiddleware mounts the jwt auth middleware onto the service.
func UseJWTMiddleware(service *goa.Service, middleware goa.Middleware) {
	service.Context = context.WithValue(service.Context, authMiddlewareKey("jwt"), middleware)
}

// NewJWTSecurity creates a jwt security definition.
func NewJWTSecurity() *goa.JWTSecurity {
	def := goa.JWTSecurity{
		In:       goa.LocHeader,
		Name:     "Authorization",
		TokenURL: "http://openshift.io/api/login/authorize",
	}
	def.Description = "JWT Token Auth"
	return &def
}

// UseJWTQueryParamMiddleware mounts the jwt-query-param auth middleware onto the service.
func UseJWTQueryParamMiddleware(service *goa.Service, middleware goa.Middleware) {
	service.Context = context.WithValue(service.Context, authMiddlewareKey("jwt-query-param"), middleware)
}

// NewJWTQueryParamSecurity creates a jwt-query-param security definition.
func NewJWTQueryParamSecurity() *goa.JWTSecurity {
	def := goa.JWTSecurity{
		In:       goa.LocQuery,
		Name:     "access_token",
		TokenURL: "http://openshift.io/api/login/authorize",
	}
	def.Description = "JWT Token Query Parameter Auth"
	return &def
}

// handleSecurity creates a handler that runs the auth middleware for the security scheme.
func handleSecurity(schemeName string, h goa.Handler, scopes ...string) goa.Handler {
	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		scheme := ctx.Value(authMiddlewareKey(schemeName))
		am, ok := scheme.(goa.Middleware)
		if !ok {
			return goa.NoAuthMiddleware(schemeName)
		}
		ctx = goa.WithRequiredScopes(ctx, scopes)
		return am(h)(ctx, rw, req)
	}
}
