// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "wit": collaborators Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-wit
// --version=v1.3.0

package client

import (
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
)

// AddCollaboratorsPath computes a request path to the add action of collaborators.
func AddCollaboratorsPath(spaceID uuid.UUID, identityID string) string {
	param0 := spaceID.String()
	param1 := identityID

	return fmt.Sprintf("/api/spaces/%s/collaborators/%s", param0, param1)
}

// Add a user to the list of space collaborators.
func (c *Client) AddCollaborators(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewAddCollaboratorsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewAddCollaboratorsRequest create the request corresponding to the add action endpoint of the collaborators resource.
func (c *Client) NewAddCollaboratorsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// AddManyCollaboratorsPath computes a request path to the add-many action of collaborators.
func AddManyCollaboratorsPath(spaceID uuid.UUID) string {
	param0 := spaceID.String()

	return fmt.Sprintf("/api/spaces/%s/collaborators", param0)
}

// Add users to the list of space collaborators.
func (c *Client) AddManyCollaborators(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewAddManyCollaboratorsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewAddManyCollaboratorsRequest create the request corresponding to the add-many action endpoint of the collaborators resource.
func (c *Client) NewAddManyCollaboratorsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// ListCollaboratorsPath computes a request path to the list action of collaborators.
func ListCollaboratorsPath(spaceID uuid.UUID) string {
	param0 := spaceID.String()

	return fmt.Sprintf("/api/spaces/%s/collaborators", param0)
}

// List collaborators for the given space ID.
func (c *Client) ListCollaborators(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListCollaboratorsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListCollaboratorsRequest create the request corresponding to the list action endpoint of the collaborators resource.
func (c *Client) NewListCollaboratorsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// RemoveCollaboratorsPath computes a request path to the remove action of collaborators.
func RemoveCollaboratorsPath(spaceID uuid.UUID, identityID string) string {
	param0 := spaceID.String()
	param1 := identityID

	return fmt.Sprintf("/api/spaces/%s/collaborators/%s", param0, param1)
}

// Remove a user from the list of space collaborators.
func (c *Client) RemoveCollaborators(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewRemoveCollaboratorsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewRemoveCollaboratorsRequest create the request corresponding to the remove action endpoint of the collaborators resource.
func (c *Client) NewRemoveCollaboratorsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// RemoveManyCollaboratorsPath computes a request path to the remove-many action of collaborators.
func RemoveManyCollaboratorsPath(spaceID uuid.UUID) string {
	param0 := spaceID.String()

	return fmt.Sprintf("/api/spaces/%s/collaborators", param0)
}

// Remove users form the list of space collaborators.
func (c *Client) RemoveManyCollaborators(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewRemoveManyCollaboratorsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewRemoveManyCollaboratorsRequest create the request corresponding to the remove-many action endpoint of the collaborators resource.
func (c *Client) NewRemoveManyCollaboratorsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}
