// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "wit": endpoints Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-wit
// --version=v1.3.0

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ListEndpointsPath computes a request path to the list action of endpoints.
func ListEndpointsPath() string {

	return fmt.Sprintf("/api/endpoints")
}

// List all endpoints.
func (c *Client) ListEndpoints(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListEndpointsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListEndpointsRequest create the request corresponding to the list action endpoint of the endpoints resource.
func (c *Client) NewListEndpointsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
