// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "wit": label Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-wit
// --version=v1.3.0

package client

import (
	"bytes"
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
)

// CreateLabelPayload is the label create action payload.
type CreateLabelPayload struct {
	Data *Label `form:"data" json:"data" xml:"data"`
	// An array of mixed types
	Included []interface{} `form:"included,omitempty" json:"included,omitempty" xml:"included,omitempty"`
}

// CreateLabelPath computes a request path to the create action of label.
func CreateLabelPath(spaceID uuid.UUID) string {
	param0 := spaceID.String()

	return fmt.Sprintf("/api/spaces/%s/labels", param0)
}

// create label with id, name and color.
func (c *Client) CreateLabel(ctx context.Context, path string, payload *CreateLabelPayload) (*http.Response, error) {
	req, err := c.NewCreateLabelRequest(ctx, path, payload)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateLabelRequest create the request corresponding to the create action endpoint of the label resource.
func (c *Client) NewCreateLabelRequest(ctx context.Context, path string, payload *CreateLabelPayload) (*http.Request, error) {
	var body bytes.Buffer
	err := c.Encoder.Encode(payload, &body, "*/*")
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	header.Set("Content-Type", "application/json")
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// ListLabelPath computes a request path to the list action of label.
func ListLabelPath(spaceID uuid.UUID) string {
	param0 := spaceID.String()

	return fmt.Sprintf("/api/spaces/%s/labels", param0)
}

// List Labels.
func (c *Client) ListLabel(ctx context.Context, path string, ifModifiedSince *string, ifNoneMatch *string) (*http.Response, error) {
	req, err := c.NewListLabelRequest(ctx, path, ifModifiedSince, ifNoneMatch)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListLabelRequest create the request corresponding to the list action endpoint of the label resource.
func (c *Client) NewListLabelRequest(ctx context.Context, path string, ifModifiedSince *string, ifNoneMatch *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if ifModifiedSince != nil {

		header.Set("If-Modified-Since", *ifModifiedSince)
	}
	if ifNoneMatch != nil {

		header.Set("If-None-Match", *ifNoneMatch)
	}
	return req, nil
}

// ShowLabelPath computes a request path to the show action of label.
func ShowLabelPath(spaceID uuid.UUID, labelID uuid.UUID) string {
	param0 := spaceID.String()
	param1 := labelID.String()

	return fmt.Sprintf("/api/spaces/%s/labels/%s", param0, param1)
}

// Retrieve label for the given id.
func (c *Client) ShowLabel(ctx context.Context, path string, ifModifiedSince *string, ifNoneMatch *string) (*http.Response, error) {
	req, err := c.NewShowLabelRequest(ctx, path, ifModifiedSince, ifNoneMatch)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowLabelRequest create the request corresponding to the show action endpoint of the label resource.
func (c *Client) NewShowLabelRequest(ctx context.Context, path string, ifModifiedSince *string, ifNoneMatch *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if ifModifiedSince != nil {

		header.Set("If-Modified-Since", *ifModifiedSince)
	}
	if ifNoneMatch != nil {

		header.Set("If-None-Match", *ifNoneMatch)
	}
	return req, nil
}

// UpdateLabelPayload is the label update action payload.
type UpdateLabelPayload struct {
	Data *Label `form:"data" json:"data" xml:"data"`
	// An array of mixed types
	Included []interface{} `form:"included,omitempty" json:"included,omitempty" xml:"included,omitempty"`
}

// UpdateLabelPath computes a request path to the update action of label.
func UpdateLabelPath(spaceID uuid.UUID, labelID uuid.UUID) string {
	param0 := spaceID.String()
	param1 := labelID.String()

	return fmt.Sprintf("/api/spaces/%s/labels/%s", param0, param1)
}

// update the label for the given id.
func (c *Client) UpdateLabel(ctx context.Context, path string, payload *UpdateLabelPayload) (*http.Response, error) {
	req, err := c.NewUpdateLabelRequest(ctx, path, payload)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUpdateLabelRequest create the request corresponding to the update action endpoint of the label resource.
func (c *Client) NewUpdateLabelRequest(ctx context.Context, path string, payload *UpdateLabelPayload) (*http.Request, error) {
	var body bytes.Buffer
	err := c.Encoder.Encode(payload, &body, "*/*")
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PATCH", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	header.Set("Content-Type", "application/json")
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}
