// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "wit": work_item_type_groups Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-wit
// --version=v1.3.0

package client

import (
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
)

// ListWorkItemTypeGroupsPath computes a request path to the list action of work_item_type_groups.
func ListWorkItemTypeGroupsPath(spaceTemplateID uuid.UUID) string {
	param0 := spaceTemplateID.String()

	return fmt.Sprintf("/api/spacetemplates/%s/workitemtypegroups", param0)
}

// List of work item type groups
func (c *Client) ListWorkItemTypeGroups(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListWorkItemTypeGroupsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListWorkItemTypeGroupsRequest create the request corresponding to the list action endpoint of the work_item_type_groups resource.
func (c *Client) NewListWorkItemTypeGroupsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
