// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "wit": work_item_board Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-wit
// --version=v1.3.0

package client

import (
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
)

// ShowWorkItemBoardPath computes a request path to the show action of work_item_board.
func ShowWorkItemBoardPath(boardID uuid.UUID) string {
	param0 := boardID.String()

	return fmt.Sprintf("/api/workitemboards/%s", param0)
}

// Show work item board for given ID
func (c *Client) ShowWorkItemBoard(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowWorkItemBoardRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowWorkItemBoardRequest create the request corresponding to the show action endpoint of the work_item_board resource.
func (c *Client) NewShowWorkItemBoardRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
