// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "wit": work_item_boards Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-wit
// --version=v1.3.0

package client

import (
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
)

// ListWorkItemBoardsPath computes a request path to the list action of work_item_boards.
func ListWorkItemBoardsPath(spaceTemplateID uuid.UUID) string {
	param0 := spaceTemplateID.String()

	return fmt.Sprintf("/api/spacetemplates/%s/workitemboards", param0)
}

// List work item boards
func (c *Client) ListWorkItemBoards(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListWorkItemBoardsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListWorkItemBoardsRequest create the request corresponding to the list action endpoint of the work_item_boards resource.
func (c *Client) NewListWorkItemBoardsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
