// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "wit": work_item_link_type Resource Client
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-wit/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-wit
// --version=v1.3.0

package client

import (
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
)

// ShowWorkItemLinkTypePath computes a request path to the show action of work_item_link_type.
func ShowWorkItemLinkTypePath(wiltID uuid.UUID) string {
	param0 := wiltID.String()

	return fmt.Sprintf("/api/workitemlinktypes/%s", param0)
}

// Retrieve work item link type (as JSONAPI) for the given link ID.
func (c *Client) ShowWorkItemLinkType(ctx context.Context, path string, ifModifiedSince *string, ifNoneMatch *string) (*http.Response, error) {
	req, err := c.NewShowWorkItemLinkTypeRequest(ctx, path, ifModifiedSince, ifNoneMatch)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowWorkItemLinkTypeRequest create the request corresponding to the show action endpoint of the work_item_link_type resource.
func (c *Client) NewShowWorkItemLinkTypeRequest(ctx context.Context, path string, ifModifiedSince *string, ifNoneMatch *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if ifModifiedSince != nil {

		header.Set("If-Modified-Since", *ifModifiedSince)
	}
	if ifNoneMatch != nil {

		header.Set("If-None-Match", *ifNoneMatch)
	}
	return req, nil
}
